### ISSUE TITLE
Problems with training on ImageNet-ESC

### ISSUE THREAD

**Issue by jesi688** [linzhiqiu/cross_modal_adaptation#16]
After successfully running audio_features.py the features.pt is generated, but when running **imagenet_esc.py** later it says that the required **classname.pth** could not be found, may I know how to generate the corresponding file?

**Comment by linzhiqiu** [comment]
Thanks for pointing this out. You might want to run features.py again to get the text features for "classname".

```
python features.py --dataset imagenet --train-shot 16 --seed 1 --clip-encoder RN50 --image-layer-idx 0 --text-augmentation classname --image-augmentation none --image-views 0
```

Let me know if it works!

**Comment by jesi688** [comment]
Aftermodification, this error occurs when training on ImageNet-ESC: 
Dataset: imagenet_27
image dataset has 1350 test examples (imagenet_27)
Traceback (most recent call last):
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 783, in <module>
    main()
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 397, in main
    test_acc = evaluate(clip_encoder, classifier_head, logit, text_dataset, test_dataset)
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 203, in evaluate
    head, _, _ = make_classifier_head(
TypeError: make_classifier_head() missing 1 required positional argument: 'text_encoder'
How can I fix it?

**Comment by linzhiqiu** [comment]
I just attempted to fix imagenet_esc.py. Could you see if the new version works?

**Comment by jesi688** [comment]
> I just attempted to fix imagenet_esc.py. Could you see if the new version works?
And with that comes this error
Dataset: imagenet_27
image dataset has 1350 test examples (imagenet_27)
Building text dataset per class...
  0%|                                                                                                                                                                                 | 0/27 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 767, in <module>
    main()
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 406, in main
    test_acc = evaluate(clip_encoder, classifier_head, logit, text_dataset, test_dataset, text_encoder)
  File "F:\code\cross_modal_adaptation-main\imagenet_esc.py", line 209, in evaluate
    head, _, _ = make_classifier_head(
  File "F:\code\cross_modal_adaptation-main\engine\model\head.py", line 109, in make_classifier_head
    linear_head.weight.data = get_zero_shot_weights(
  File "F:\code\cross_modal_adaptation-main\engine\model\head.py", line 68, in get_zero_shot_weights
    text_dataset_per_class, _ = get_text_dataset_per_class(text_dataset)
  File "F:\code\cross_modal_adaptation-main\engine\model\head.py", line 56, in get_text_dataset_per_class
    for text, text_label, eot_indices in tqdm(text_dataset):
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by linzhiqiu** [comment]
I updated it again by reverting to my older make_classifier_head() function, hopefully it is fixed this time. Sorry that I didn't have the same machine when I tested this code, so my debugging capabilities are limited.

**Comment by jesi688** [comment]
Thank you for your many replies, after downloading the latest version of the code I am able to run it successfully, thank you for your help!
